---
title: "Red and Black 190224 : Intro. Statistics"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
```

## Data

```{r, data}
class_roll <- read.xlsx("../data/class_roll_intro190224.xlsx", 
                        sheetIndex = 1, 
                        startRow = 2, endRow = 78, 
                        colIndex = c(3:7, 9), colClasses = rep("character", 6), 
                        encoding = "UTF-8",
                        stringsAsFactors = FALSE)
str(class_roll)
names(class_roll) <- c("dept", "id", "name", "year", "email", "cell_no")
str(class_roll)
```

## Randomization

```{r, randomization}
set.seed(2)
N <- nrow(class_roll) 
class_roll$group <- 1:N %>%
  sample %>%
  `%%`(2) %>%
  factor(levels = c(0, 1), labels = c("Red", "Black"))
```

## 학번

```{r, id}
class_roll %$%
  table(.$group, .$id %>% substr(1, 4)) %>%
  pander
class_roll$id %>%
  substr(1, 4) %>%
  `>=`(2019) %>%
  ifelse("19학번", "18학번 이전") %>%
  factor(levels = c("19학번", "18학번 이전")) %>%
  table(class_roll$group, .) %>%
  pander
```

## 학번 홀짝

```{r, odd or even}
class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) %>%
  pander
```

## e-mail 서비스업체

```{r, e_mail}
class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  table(class_roll$group, .) %>%
  pander
```

## 전화번호의 분포

```{r}
cell_numbers <- class_roll$cell_no %>%
  substr(start = 10, stop = 13) %>%
  sapply(as.numeric) 
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), sep = "~")
cell_numbers %>%
  cut(labels = cut_label, breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group) %>%
  t %>%
  pander
cell_numbers %T>%
  hist(main = "Histogram of Cell Phone Numbers") %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table %>%
  chisq.test %>%
  pander
```

## 성씨 분포

```{r, name}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
f_name %>%
  table(class_roll$group, .) %>%
  pander
```

## 많이 나오는 성씨

```{r, frequent names}
f_name %>%
  `%in%`(c("김", "이", "박")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "기타")) %>%
  table(class_roll$group, .) %>%
  pander
```

## 학과

```{r, departments}
class_roll %$%
  table(.$group, .$dept) %>%
  pander
```

## 주요 학과와 기타

```{r, main departments}
class_roll$dept %>%
  `==`("간호학") %>%
  ifelse("간호학", "기타") %>%
  table(class_roll$group, .) %>%
  pander
```

<P style="page-break-before:always">

## 전체 명단 : 가나다순

```{r, echo = TRUE}
class_roll$name %>%
  order %>%
  class_roll[., c("id", "name", "group")] %<>%
  `colnames<-`(c("학번", "이름", "그룹")) %>%
  pander(row.names = FALSE)
```

<P style="page-break-before:always">

## 전체 명단 : 그룹 단위 가나다순

```{r, list, echo = TRUE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("id", "name", "group")] %<>%
  `colnames<-`(c("학번", "이름", "그룹")) %>%
  pander(row.names = FALSE)
```

<P style="page-break-before:always">

## 집단별 출석부

```{r, red_names, echo = TRUE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("id", "name", "group")] %>%
  subset(.$group == "Red", select = c("id", "name")) %<>%
  `colnames<-`(c("학번", "이름")) %>%
  pander(caption = "Red")
```

<P style="page-break-before:always">

```{r, black_names, echo = TRUE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("id", "name", "group")] %>%
  subset(.$group == "Black", select = c("id", "name")) %<>%
  `colnames<-`(c("학번", "이름")) %>%
  pander(caption = "Black")
```

<!--
```{r, save}
save.image("./red_and_black_intro_190224_data.RData")
```
-->