---
# title: "Red and Black 190226"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr", repos = "https://cran/rstudio.com")
library(xlsx)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide"}
load("./red_and_black_intro_190224_data.RData")
```

### 학번

```{r, id, echo = FALSE}
class_roll %$%
  table(.$group, .$id %>% substr(1, 4)) %>%
  pander
class_roll %$%
  substr(.$id, 1, 4) %>%
  `>=`(2019) %>%
  ifelse("younger_19", "older_19") %>%
  factor(levels = c("younger_19", "older_19")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 19학번 기준

```{r, echo = FALSE}
class_roll$id %>%
  substr(1, 4) %>%
  `>=`(2019) %>%
  ifelse("younger_19", "older_19") %>%
  factor(levels = c("younger_19", "older_19"),
         labels = c("19학번", "18학번 이전")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 학번 홀짝

```{r, odd or even, echo = FALSE}
class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) %>%
  pander
```

### e-mail 서비스업체

```{r, e_mail, echo = FALSE}
class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  table(class_roll$group, .) %>%
  pander
```

### 전화번호의 분포

```{r, echo = FALSE}
cell_numbers <- class_roll$cell_no %>%
  substr(start = 10, stop = 13) %>%
  sapply(as.numeric)
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
cell_numbers %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) %>%
#   t %>%
  kable
cell_numbers %>%
  hist(main = "Histogram of Cell Phone Numbers")
cell_numbers %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table %>%
  chisq.test %>% 
  pander
```

<!--
### 성씨 분포

```{r, name, echo = FALSE}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
f_name %>%
  table(class_roll$group, .) %>%
  pander
```
-->

### 많이 나오는 성씨

```{r, frequent names, echo = FALSE}
f_name %>%
  `%in%`(c("김", "이", "박")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "기타")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 학과

```{r, departments, echo = FALSE}
# pander(class_roll)
class_roll %$%
  table(.$group, .$dept) %>%
  pander
```

<!--
### 전체 출석부

```{r}
class_roll %$%
  order(.$name) %>%
  class_roll[., c("id", "name", "group")] %>%
  pander(caption = "가나다순", row.names = FALSE)
```

<P style="page-break-before:always">

```{r, echo = FALSE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Red", select = c("id", "name")) %>%
  pander(caption = "Red")
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Black", select = c("id", "name")) %>%
  pander(caption = "Black")
```

### 전체 출석부(가나다순)

```{r, eval = TRUE}
class_roll.order <- class_roll[order(class_roll$name), ]
pander(class_roll.order)
nrow(class_roll.order)
class_roll.group <- class_roll[order(class_roll$group, class_roll$name), ]
pander(class_roll.group)
```

<P style="page-break-before:always">

<!--
```{r, save}
save.image("./red_and_black_190317_data.RData")
```
-->
